### PR TITLE
Square and TND volume mixing for accuracy

### PR DESCRIPTION
**Pull request by GreatGlobox**
- Square volumes are now mixed much more accurately vs the real hardware.
- Expansion audio was separated to its own blip buffer to make the mixing possible.
- Square synth volume is set to be fixed, and mixer adjustments for squares will follow tnd_volume.
- Set the noise blip quality to good (it seems much closer to that of the hardware from testing).
- Inverted the triangle phase (it actually resets to level 15 on the real hardware, not 0).
- Added a workaround to remove the initial triangle pop.
- Changed TND to 196 (2.75 * 15 + 1.85 * 15 + 127), results in values closer to 22638 (DMC) per volume step.

_**Note:** The inverted triangle phase means TND starts on 41.25 (new TND settings with 15 * 2.75), which affects the volume of Noise and DPCM most notably in songs with no triangle. This matches up with what the hardware is doing, and triangle on my Famicom seems to always start on 15 regardless as to whether I power it on or press reset._

_**Note 2:** The new TND settings have been tested across various DAC volumes, including different triangle phase etc. It's much closer to the hardware, in terms of contrast between triangle, noise, and DMC channel volumes. It is possible to make it do the exact same mixing as NSFPlay, but this seems far more accurate judging from empirical measurements._

___

To explain where 196 comes from in depth:
```
Triangle = 8227
Noise    = 12241
DMC      = 22638

22638 / 8227  = 2.751671326121308
22638 / 12241 = 1.849358712523487
```
If we used these exact numbers, each volume step would be the equivalent to a step in DMC:
```
8227  * 2.751671326121308 = 22638
12241 * 1.849358712523487 = 22638
```
However, this results in a somewhat confusing max TND, and a lot of numbers with many decimal places:
```
15 * 2.751671326121308 + 15 * 1.849358712523487 + 127 = 196.01545057967192
```
Rounding them to 2 decimal places produces the same results in terms of volume, and seems more sensible than using a confusing number for max TND:
```
8227  * 2.75 = 22624.25 (originally 3 * 8227  = 24681)
12241 * 1.85 = 22645.85 (originally 2 * 12241 = 24482)
```
This gives us a new max TND of 196:
```
15 * 2.75 + 15 * 1.85 + 127 = 196
```
The exact figures could be used, but the results from the rounded values seem the same in testing.

### CODE REVIEW

**Comment by BleuBleu** [comment]
Hi. Unless im mistaken, this PR is badly outdated, could you refresh it to latest 4.3.0 so its easier for me to do a review?

-Mat

**Comment by GreatGlobox** [comment]
I tried to merge there to see if that helps. The only changes in this should be related to NesSndEmu, aside from one change to the Linux csproj file which isn't even needed anyway as it was only removing a duplicate line.

**Comment by BleuBleu** [comment]
Small questions/corrections:

- When mixing the squares, why do we multiply by the TND volume? `pack_sample(mix_squares(unpack_sample(sq_accum)) * tnd_volume);`
- Things like `if (expansions & expansion_mask_vrc6 | expansion_mask_vrc7 | expansion_mask_mmc5 | expansion_mask_namco | expansion_mask_sunsoft)` will not compile on clang. Add parhentesis around the | to clearly shows OR needs to be done before AND.
- Move `if (out)` outside of for loop in at end of `Simple_Apu::read_samples`. No point of looping and testing the same thing over and over.
- Explain TND skip a bit more. Is it a hack? Or a real hardware feature?

**Comment by GreatGlobox** [comment]
Multiplying by tnd_volume was a workaround so that the volume mixer will still control the square volume. It seemed simpler than adding another variable that wasn't needed.

I will fix this later then yeah, that will be a simple workaround to add parentheses.

I will also look at this in a bit and try rectify it.

OK so the tnd_skip is a bit of a hack but I will explain. Triangle on the real Famicom starts on 15 and not 0, it also resets to 15 when you reset the console. This affects how the volume of everything else is within TND and replicates the hardware. The reason I used this hack is because starting the triangle on 15 caused a pop, and this was just silencing the first 12 samples (which haven't started playing any audio yet anyway). I wasn't sure if there was a better workaround for this.

**Comment by BleuBleu** [comment]
Got it.

Dont touch the "out" thing for FDS. The FDS filter is still updated when there is no output, so when you mute/unmute it, at least the filter will be a correct state when you unmute.

-Mat

**Pull request merged**
