### PR TITLE
Register view, EPSM SSG pitch table & emu2149 improvements

### PR DESCRIPTION
**Pull request by ADM228**
VGM export works now (wahoo)
EPSM SSG pitch table now doesn't have the hacky 1.004 multiplier
Register view now has envelope pitch and a graph of its shape
emu2149 updated to its 2022 version *and* improved upon that
Linux .csproj file stuff

### CODE REVIEW

**Comment by ADM228** [comment]
Actually wait; gotta check more linux *.csproj files

**Comment by BleuBleu** [comment]
Some question/comments:
- Why dont we simply draw the image for the envelope in the register viewer? This drawing with a LUT is over engineered. We are now almost doing emulation in the reg viewer. I dont want it.
- Why re-add the clamp in Nes_Sunsoft, the values cannot go higher.
- Can you back your emu2149 changes by data. We are now going to diverge from other emulators/nsf players, we need to be able to say "yes, but gimmick REALLY sounds like that". Otherwise remove the changes.
- Remove binaries from PRs

**Comment by ADM228** [comment]
1. We can just draw a pre-existing image? didn't know that
2. i re-added the clamp just in case the emulation goes rogue or something (albeit it can be argued that that is unnecessary)
3. There are several things that i definitely can back up by my real YM2149s:
- the noise generator swapout
- the envelope generator bugfix
- the volume table/envelope shape shift
Ask for any other ones that need to be tested (and also we could probably ask forple for S5B data)
4. Will do when we agree on points 2 and 3 completely

**Comment by BleuBleu** [comment]
Yeah just draw the little pitures that we already have for envelopes.
```
var bmp = c.Graphics.GetTextureAtlasRef($"S5BEnvelope8{x}");
c.DrawTextureAtlas(bmp, posX, posY);
```

**Comment by BleuBleu** [comment]
Thank you!

**Pull request merged**
