### PR TITLE
Import FTI files

### PR DESCRIPTION
**Pull request by Waik0**
Hello!
I talked on Twitter before.
Thank you for the polite response at that time.
This is a proposal for adding functions.

### Changes
Feature addition

### Overview
Added script to import famitracker instrument file

### Details

Added FamiStudio\Source\IO\FamitrackerInstrumentFile.cs
Supports FTI type 2A03
Supports FTI version 2.0-2.4
On the UI, it is set to the "+" button on the left side of the Instrument header.

### Known issues

HighPitch, DutyCicle and Setting are ignored.
Pitch behavior is different from FamiTracker.
Not compatible with versions older than 2.0

### Test
Windows build: Yes
Mac OS build: Yes
NSF export: Yes(check on windows)

### CODE REVIEW

**Comment by BleuBleu** [comment]
Hello! Yes of course I remember. I am busy this week with work, I will definitely take a look and integrate this over the weekend (or ask for minor changes if I feel picky!). 

Thanks so much for the help, I will get back to you saturday or sunday.

-Mat

**Comment by Waik0** [comment]
Thank you for your prompt response.
I am looking forward to weekend.
Good luck with your work.

**Comment by BleuBleu** [comment]
Hi!

I took some time to look at the change. Looks good, but I do have a question:

- Are you sure pitch envelopes are converted correctly when importing from the FTI? FamiTrackers stores relative envelopes (for example, an envelope with a single value of +1 that loops would make the pitch go higher and higher) where as FamiStudio uses absolute envelopes. When I import the FamiTracker text file I have do to this. Do we need to do it for instrument files to?

Also, small detail, do you mind if I change the icon? Have 2 + + signs is kind of confusing! :)

Icon

-Mat

**Comment by Waik0** [comment]
Thank you for confirming the change.

・If my interpretation is correct...
I was assigning the value read from the FTI file as it is as the Pitch value.
I need a fix to convert like when FamiStudio exports FamiTrackerTextFile.
For example:

```
 Fami Studio : 0  1  2  1  0
 Fami Tracker: 0  1  1 -1 -1
```

If so, I will fix it and contact you again.

・I probably couldn't make icon, so I just wanted a import icon. Thank you so much!

**Comment by BleuBleu** [comment]
Yes! Actually, take a look at the function "ConvertToAbsolute". I think it already does exactly that. I'm on my phone now so I can't check for sure.

-Mat

**Comment by Waik0** [comment]
Thank you for the information. I used that function and confirmed that it was converted correctly.

**Comment by BleuBleu** [comment]
Awesome! I'll integrate this latest version a night this week. I made some good progress on copy/paste by the way. Should not be too far from your little animation you made.

Thanks again for contributing.

-Mat

**Comment by Waik0** [comment]
Thank you!
And its very good news! I look forward to using the feature in the latest version.

**Comment by BleuBleu** [comment]
Hi! I finally took the time to integrate your change. If you have some time. I think it would be nice to import the first value of the Duty cycle. FamiStudio does not support duty envelope, but taking the first value would be better than nothing. Right now it is completely ignored.

**Comment by Waik0** [comment]
Sure.
I will send the modification as another pull request next week.
Thank you for integrate changes!

**Pull request merged**
