### PR TITLE
GLFW Hotfix for Linux

### PR DESCRIPTION
**Pull request by GreatGlobox**
- ~~Updated included libglfw.so to version 3.4~~ Reverted since some distros don't use GLFW 3.4 just yet
- Added window hint for Wayland icon
- Changed some Linux cursors to GLFW_RESIZE_ALL_CURSOR
- Added a check for GLFW version under Linux; only use xcursor code if GLFW version < 3.4
- Added some new GLFW constants and changed some constant names to their newer counterparts
- Added an attempt to load rtmidi 6 on Linux
- Added a check for system GLFW on Linux; fallback on included binary if not found
- Added a fix for pasting instruments with folders
- Recreated Journey to Silius Demo Song with more accurate volume envelopes
- Fixed some wrongly placed DPCM notes in Gimmick Demo Song

### CODE REVIEW

**Comment by BleuBleu** [comment]
I want to merge this for next weekend. It looks good, im just wondering why you just handled the case for instrument forlders? There are 4 types of folders. Im pretty sure all of them will crash.

**Comment by GreatGlobox** [comment]
No problem. For folders, I had only encountered the issue with pasting an instrument, but that's a good point. I'll try to amend this too.

**Comment by GreatGlobox** [comment]
I had attempted making EnsureAllFoldersExist public and calling it as a test. It seemed to get as far as creating the instrument folder, then it would try to iterate an extra time for some reason (despite already reaching the last instrument) and just hang there. The debugger would just disconnect at that point and I would have to force close the program.

I'll try to look into it further. If I don't manage to figure it out, I'll remove the folder fix for now and leave it for when you have time.

**Comment by BleuBleu** [comment]
Yeah, when creating missing folders, it may trigger a re-sorting if auto-sort is enabled, so elements may change order. I will likely merge and change it on my end.

**Pull request merged**
